### ISSUE TITLE
【建议】建议使用正则响应器匹配事件

### ISSUE THREAD

**Issue by Jerry-FaGe** [mengshouer/nonebot_plugin_analysis_bilibili#1]
如题
如果解析所有消息的话一是占用性能二是很有可能与某些同样解析所有消息闲聊功能产生未知冲突

另外B站QQ小程序json可能有更新，现在的正则匹配不到了
`QQ小程序&amp;#93;哔哩哔哩` -> `QQ小程序&#93;哔哩哔哩`

**Comment by mengshouer** [comment]
之前nb1的时候，正则匹配无法完整匹配，我就改成了解析所有(过几天我再看看还有没有这个问题。

**Comment by mengshouer** [comment]
https://github.com/mengshouer/nonebot_plugin_analysis_bilibili/commit/1469ef48742b71e0d7cbfdb7bd220c0cc0cdcc16
