### ISSUE TITLE
[功能添加]可以添加一个自动撤回原消息的功能吗？

### ISSUE THREAD

**Issue by RemKeeper** [mengshouer/nonebot_plugin_analysis_bilibili#14]
b站现在发送的大多分享都带跟踪信息，一点击双方都被标记上了，就开始胡乱推送
解析后的是不带追踪信息的，可以撤回发送的原消息以达到反追踪的目的吗

**Comment by NekoAria** [comment]
实现是容易，但是前提是机器人需要是群管理员，不然没有撤回消息的权限。

另外还有个问题是，群主发的消息好像只有自己能撤回。

如果你是群主，除非你自己撤回，不然也没意义。

**Comment by mengshouer** [comment]
功能用处不大+考虑跨平台兼容性问题，暂不考虑（
