### ISSUE TITLE
feature: 添加是否使用代理选项

### ISSUE THREAD

**Issue by 050644zf** [mengshouer/nonebot_plugin_analysis_bilibili#16]
起因是 #15 ，在此之后很长一段时间都有这个问题，虽然我没开代理但可能仍然有设置被动到导致无法联网

然后我找到了 [同样的报错的解决方案](https://stackoverflow.com/questions/63347818/aiohttp-client-exceptions-clientconnectorerror-cannot-connect-to-host-stackover)

我把

https://github.com/mengshouer/nonebot_plugin_analysis_bilibili/blob/b1d17586c7b95b46ddb57ccc23a21c2b76f460b6/nonebot_plugin_analysis_bilibili/analysis_bilibili.py#L121

修改为

```python
async with aiohttp.ClientSession(trust_env=True) as session:
```

之后就能正常访问了。

考虑到使用代理的场景不少，我推荐把这个加到配置项去。

**Comment by mengshouer** [comment]
b23链接重定向返回并不会走 Line 121 里面。search_bili_by_title 的作用是，一开始 qq 分享的小程序是不带视频链接的，所以通过搜索标题查找视频，而且现在那个搜索 api 也有点问题，之前改了一次，后面官方又加了鉴权，我想着这边没有单独加搜视频的功能，所以我就没更新（因为现在分享的小程序都带b23链接了）。如果你是只改了 Line 121 的话，那就说明不是代理问题。

**Comment by 050644zf** [comment]
好像确实是，主要现在就是启动机器人时还能解析，过一阵子又不行，搞得我以为奏效了

https://github.com/HibiKier/zhenxun_bot/issues/1194 不是一个插件，但别人也遇到过同样的问题。现在基本上就是随缘解析。

**Comment by mengshouer** [comment]
看了一眼 trust_env 这个参数，这个参数是读取的环境变量内的相关的代理参数，正常情况下没有人会手动设置。即使你用的 *ray 或者 clash ，不开 tun 的情况下，使用的也只是系统的代理，trust_env 并不会生效。
