### ISSUE TITLE
解析动态、专栏、直播时出现异常

### ISSUE THREAD

**Issue by lunzima** [mengshouer/nonebot_plugin_analysis_bilibili#2]
受影响版本：1.1.2

![QQ截图20210702191024](https://user-images.githubusercontent.com/32062239/124266142-2bee0400-db69-11eb-8d9c-1fbccfbf967f.png)
原链接形如：https://www.bilibili.com/read/cv11952127

而且会直接把Python异常处理信息输出

**Comment by mengshouer** [comment]
其他插件的问题吧？我自己测试了一遍，未响应这条消息

**Comment by mengshouer** [comment]
e02c95206ffb5e594c47a88d522fbc8c7f0b126c  添加直播和专栏解析了
