### ISSUE TITLE
黑名单和群黑名单失效

### ISSUE THREAD

**Issue by Yangleis** [mengshouer/nonebot_plugin_analysis_bilibili#23]
看了下代码，读取配置时候黑名单是读成str，但是比对user_id、group_id是int。
修改为相同类型，测试可以正常屏蔽。

**Comment by mengshouer** [comment]
5d48e9b829eabb4013dc54b0d14fcde76d9baf84

**Comment by Yangleis** [comment]
> [5d48e9b](https://github.com/mengshouer/nonebot_plugin_analysis_bilibili/commit/5d48e9b829eabb4013dc54b0d14fcde76d9baf84)

还有群号啊，这光改了用户
