### ISSUE TITLE
收到消息报错

### ISSUE THREAD

**Issue by xuehuyue** [mengshouer/nonebot_plugin_analysis_bilibili#25]
![IMG_20240704_181556](https://github.com/mengshouer/nonebot_plugin_analysis_bilibili/assets/146502308/8f92f07c-bbfb-44be-93d4-dace6196273e)

**Comment by mengshouer** [comment]
nonebot版本？qq？什么协议？用的什么适配器？

**Comment by xuehuyue** [comment]
nonebot
按照手册里面安装。
QQ?（看不懂）
mirai2适配器
ws//?

**Comment by mengshouer** [comment]
更新一下版本看看，如果用的是nb-cli的话，到nonebot目录跑一遍

```sh copy
nb plugin update nonebot_plugin_analysis_bilibili -i https://pypi.org/simple
```

自建环境的话，自己用 pip 更新吧，指定一下 index-url，刚推上去镜像源可能还没同步，反正版本是2.7.1

```sh copy
pipx install --upgrade nonebot_plugin_analysis_bilibili --index-url https://pypi.org/simple 
```

**Comment by xuehuyue** [comment]
![Screenshot_20240704_232615](https://github.com/mengshouer/nonebot_plugin_analysis_bilibili/assets/146502308/aba1fce1-0d88-4bd0-8e17-8d002c4780b6)
![Screenshot_20240704_233259](https://github.com/mengshouer/nonebot_plugin_analysis_bilibili/assets/146502308/e03bffb9-cdcc-48ef-80f8-a9c535285a64)
还是不行

**Comment by xuehuyue** [comment]
【【老图合集】老车万人的厨力-哔哩哔哩】 https://b23.tv/KhY115u
分享的小程序

**Comment by mengshouer** [comment]
再更新看看 2.7.2

**Comment by xuehuyue** [comment]
正常了，谢谢
注意身体
