### ISSUE TITLE
多个机器人重复发送链接

### ISSUE THREAD

**Issue by moli721** [mengshouer/nonebot_plugin_analysis_bilibili#28]
在一个具有多个机器人的群里，在分享一个bibli视频之后，由于一个机器人发送的内容包含链接，其他机器人识别到这个链接之后又会再次发送此链接，造成无限循环
设置了`analysis_reanalysis_time = 0 # 同一个视频重新解析时间，单位秒，0为不重新解析，example: 60`或者
`analysis_reanalysis_time = 60`均没有效果

**Comment by mengshouer** [comment]
analysis_reanalysis_time 是判断上一个链接，而不是之前的所有链接，我晚点改一下吧

**Comment by moli721** [comment]
![1727108349276](https://github.com/user-attachments/assets/daf2877b-c237-4baf-b45a-6ae5ee5d95e9)

理论上这部分代码在判断相同的链接就会不重复解析，但是可能由于每个机器人发送的链接不一样导致的，这里是更详细的情况

![1](https://github.com/user-attachments/assets/a4f528e0-bd5f-4c66-b846-bdbfbb5b7d3c)

**Comment by mengshouer** [comment]
更新一下插件看看，现在是给了 analysis_reanalysis_time 才有不重复解析，现在在适配之前的逻辑，如果你配置了 analysis_reanalysis_time 可以先更新着用着

**Comment by moli721** [comment]
好的，但是已经关电脑了，明天测试一下
