### ISSUE TITLE
Wrong regex result for BVid

### ISSUE THREAD

**Issue by Gaomengkai** [mengshouer/nonebot_plugin_analysis_bilibili#4]
`analysis_bilibili.py` Line 62:
```
bvid = re.compile(r'BV([a-zA-Z0-9])+', re.I).search(text)
```
This pattern will match a wrong string like `'Bvid'`. 
Sample message:
```
华洛不会飞 投稿了新视频啦
标题：《  哈哈 我先润了  》
Bvid：BV1Zu411o7RB
直链：https://www.bilibili.com/video/BV1Zu411o7RB
```
This string will cause a wrong result. We know bvid has a 10-digit unique id. So we can change the pattern into
```
bvid = re.compile(r'BV([a-zA-Z0-9]{10})+', re.I).search(text)
```

**Comment by mengshouer** [comment]
![V_NK~XBD``HT8L5YJ}ET`95](https://user-images.githubusercontent.com/36481080/139533581-2feab19b-f60b-4593-acb0-75875ecca9f6.png)

**Comment by Gaomengkai** [comment]
oe, while sending the entire message, it will return an ERROR
