### ISSUE TITLE
发送者版本过低，无法展示内容

### ISSUE THREAD

**Issue by czw63** [mengshouer/nonebot_plugin_analysis_bilibili#5]
我在群里发送哔哩哔哩链接时回复了这个和不带图片的解析
为什么呢

**Comment by mengshouer** [comment]
其他插件吧，我的插件回复的文字只有解析，和XX解析出错

**Comment by mengshouer** [comment]
找到问题了(https://github.com/Mrs4s/go-cqhttp/issues/1128
