### ISSUE TITLE
您好，关于图片问题想请教一下

### ISSUE THREAD

**Issue by jamyido** [mengshouer/nonebot_plugin_analysis_bilibili#6]
那个关于B站封面获取您最下面显示的插件在使用时出现了“视频解析出错--Error”
![image](https://user-images.githubusercontent.com/76118866/183679463-ef2846dc-eae8-45da-8908-41404e29001c.png)
显示错误代码为：'NoneType' object has no attribute 'strftime'
我该如何解决，亦或者作者您何时能使本插件原生支持封面获取

**Comment by NekoAria** [comment]
最新提交已修正

**Comment by mengshouer** [comment]
a96e4cb9d64a4e15ae56d0680e412030154d4ad0

感觉应该没有多少旧版的了，顺便写了得了
